// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package models

import (
	"time"
)

type Category struct {
	ID        int64
	Name      string
	CreatedAt time.Time
}

type Transaction struct {
	ID          int64
	CategoryID  int64
	AmountCents int64
	Note        string
	CreatedAt   time.Time
}
